//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP4
{
    using System;
    using System.Collections.Generic;
    
    public partial class acheter
    {
        public int IDSERVICE { get; set; }
        public int IDPRODUIT { get; set; }
        public int QUANTITÉ { get; set; }
    
        public virtual course course { get; set; }
        public virtual produit produit { get; set; }
    }
}
