//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP4
{
    using System;
    using System.Collections.Generic;
    
    public partial class formation
    {
        public int IDSERVICE { get; set; }
        public string LIBELLECOMPETENCE { get; set; }
        public string NBHEURES { get; set; }
        public short VISIOCONF { get; set; }
        public string PREREQUIS { get; set; }
    
        public virtual service service { get; set; }
    }
}
