//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ap4Entities : DbContext
    {
        public ap4Entities()
            : base("name=ap4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<course> course { get; set; }
        public virtual DbSet<departement> departement { get; set; }
        public virtual DbSet<formation> formation { get; set; }
        public virtual DbSet<inscrit> inscrit { get; set; }
        public virtual DbSet<loisirs> loisirs { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<repondre> repondre { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<tache_menagere> tache_menagere { get; set; }
        public virtual DbSet<transport> transport { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<type_loisirs> type_loisirs { get; set; }
        public virtual DbSet<type_tache_menagere> type_tache_menagere { get; set; }
        public virtual DbSet<ville> ville { get; set; }
        public virtual DbSet<nbInscritsTemps> nbInscritsTemps { get; set; }
    }
}
