//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP4
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int IDMESSAGE { get; set; }
        public int IDINSCRIT { get; set; }
        public string LIBELLEMESSAGE { get; set; }
        public short TRAITER { get; set; }
    
        public virtual inscrit inscrit { get; set; }
    }
}
