//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tache_menagere
    {
        public int IDSERVICE { get; set; }
        public int IDTACHE { get; set; }
        public string DESCTACHEM { get; set; }
        public string MATERIEL { get; set; }
    
        public virtual service service { get; set; }
        public virtual type_tache_menagere type_tache_menagere { get; set; }
    }
}
