//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP4
{
    using System;
    using System.Collections.Generic;
    
    public partial class transport
    {
        public int IDSERVICE { get; set; }
        public string POINTDEPART { get; set; }
        public string POINTARRIVEE { get; set; }
        public string MOTIF { get; set; }
        public short NBPLACESDISPO { get; set; }
        public short VEHICULE { get; set; }
    
        public virtual service service { get; set; }
    }
}
